AWSTemplateFormatVersion: 2010-09-09
Description: creating resources in yaml using aws cloudformation

Resources: 
  myvpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.1.0.0/16"
      EnableDnsHostnames: "true"
      EnableDnsSupport: "true"
      Tags: 
        - Key: Name
          Value: EmiVPC
  
  mysubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "us-east-1a"
      CidrBlock: "10.1.1.0/24"
      MapPublicIpOnLaunch: true
      Tags: 
        - Key: Name
          Value: EmiSubnet1public
      VpcId: 
        Ref: myvpc

  mysubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "us-east-1a"
      CidrBlock: "10.1.2.0/24"
      MapPublicIpOnLaunch: false
      Tags: 
        - Key: Name
          Value: EmiSubnet1private
      VpcId: 
        Ref: myvpc 
