AWSTemplateFormatVersion: 2010-09-09
Description: creating resources in yaml using aws cloudformation

Resources: 
  myvpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.1.0.0/16"
      EnableDnsHostnames: "true"
      EnableDnsSupport: "true"
      Tags: 
        - Key: Name
          Value: EmiVPC
  
  mysubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "us-east-1a"
      CidrBlock: "10.1.1.0/24"
      MapPublicIpOnLaunch: true
      Tags: 
        - Key: Name
          Value: EmiSubnet1public
      VpcId: 
        Ref: myvpc

  mysubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "us-east-1a"
      CidrBlock: "10.1.2.0/24"
      MapPublicIpOnLaunch: false
      Tags: 
        - Key: Name
          Value: EmiSubnet1private
      VpcId: 
        Ref: myvpc 

  mysg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allows SSH, HTTP & HTTPS to host instance" 
      GroupName: "webserver-sg"
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      Tags: 
        - Key: Name
          Value: cf-instance-sg
      VpcId: 
        Ref: myvpc

  myec2:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: "us-east-1a"
      BlockDeviceMappings:
        -
          DeviceName: /dev/xvda
          Ebs:
            VolumeType: gp2
            DeleteOnTermination: true
            VolumeSize: 10
      DisableApiTermination: false
      EbsOptimized: false
      IamInstanceProfile: "EC2-AmazonS3ReadOnlyAccess"
      ImageId: "ami-00c39f71452c08778"
      InstanceType: "t2.micro"
      KeyName: "linux-keypair"
      SecurityGroupIds: 
        - Ref: mysg
      SubnetId: 
        Ref: mysubnet
      Tags: 
        - Key: Name
          Value: Emidinho-WebServer
        - Key: CreatedBy
          Value: Emidinho
      Tenancy: "default"
      UserData: 
        Fn::Base64:  
          #!/bin/bash
          sudo su
          yum update -y
          yum install -y httpd.x86_64
          systemctl start httpd.service
          systemctl enable httpd.service
          echo "emidinho did this from cloudformation " > /var/www/html/index.html

  mybuc:
    Type: 'AWS::S3::Bucket'
    Properties: 
      AccessControl: Private 
      BucketName: emi-buc-buc
      Tags:
        - Key: Name
          Value: emi-buc-buc
